### ISSUE TITLE
It is not possible to detach emoji connected by a Zero-width joiner

### ISSUE THREAD

**Issue by yisibl** [slevithan/emoji-regex-xs#1]
I manually inserted ZWJ characters between each emoji, and the Emoji specification is terrible and doesn't seem to specify how this is handled.

```js
const emojiRegex = require('emoji-regex-xs');

const text = `
👻‍👻‍👻‍👻‍👻‍👻‍👻‍👻
`;

const regex = emojiRegex();
for (const match of text.matchAll(regex)) {
  const emoji = match[0];
  console.log(`Matched sequence ${ emoji } — code points: ${ [...emoji].length }`);
}

/**
 * Output:
   Matched sequence 👻‍👻‍👻‍👻‍👻‍👻‍👻 — code points: 15
*/
```

**Comment by slevithan** [comment]
In the absence of more specific details from the Emoji specification, this handling seems fine/correct to me. You are explicitly combining the emoji into a grapheme cluster using ZWJs. This is what enables platform-specific emoji like [women wrestling: light skin](https://emojipedia.org/women-wrestling-light-skin-tone#designs).
